name: Auto Update Playlist from API

on:
  schedule:
    - cron: '0 * * * *'  # প্রতি ঘন্টায় রান করবে
  workflow_dispatch: # ম্যানুয়ালি রান করার অপশন

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: রিপোজিটরি ক্লোন করুন
        uses: actions/checkout@v3

      - name: API থেকে নতুন প্লেলিস্ট ডাউনলোড করুন
        run: |
          curl -H "Authorization: Bearer ${{ secrets.API_TOKEN }}" -o playlist.m3u "https://your-api.com/get_playlist"

      - name: পরিবর্তন থাকলে Git Commit এবং Push করুন
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add playlist.m3u
          git commit -m "Auto-updated playlist from API" || echo "No changes to commit"
          git push

